services:
  magni_dev:
    build:
      context: ..
      dockerfile: docker/ros2-magni-base/Dockerfile
    volumes:
      - ../src:/magni_ros2_ws/src:rw
      - ../config:/magni_ros2_ws/config:ro
    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      colcon build --symlink-install &&
      source install/setup.bash &&
      bash
      "
    network_mode: host